spring:
  application:
    name: TodoApplication

  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root@123

  mail:
    host: smtp.gmail.com
    port: 587
    username: kunalsupekar965@gmail.com
    password: pott whqf mire lkjw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true # Ensure STARTTLS is required

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

jwt:
  secret: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf
  expiration: 3600000  # JWT token expiration in milliseconds (1 hour)
  refresh-token:
    expiration: 86400000  # Refresh token expiration in milliseconds (1 day)
