spring:
  application:
    name: employeeManagementSystem

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root@123

  mail:
    host: smtp.gmail.com
    port: 587
    username: kunalsupekar965@gmail.com
    password: pott whqf mire lkjw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true # Ensure STARTTLS is required

#  jpa:
#   properties:
#     hibernate:
#       dialect: org.hibernate.dialect.MySQL8Dialect
#   hibernate:
#     ddl-auto: update

server: 
  port: 5000

aws:
  accessKeyId: AKIAZ5TC4XQ6ZI4TWBZS
  secretAccessKey: 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
  s3:
    bucketName: employee-management-system-fileupload
    region: ap-south-1